### PR TITLE
➕ Add TypeScript

### PR DESCRIPTION
**Pull request by mrana17**
- Added .tsconfig.json with default config
- Installed TypeScript with `npm install --save-dev typescript @types/react @types/node`
- `npm run dev`to fill tsconfig.json
- changes .js files to .ts/.tsx

### CODE REVIEW

**Review by fre-ben — APPROVED** [review]
Looks good - GJ! 👍

**Review by saschahaselhuhn — APPROVED** [review]
gj

**Review by m-wiemers — APPROVED** [review]
Seems to be something big ☀

**Review by lmachens — APPROVED** [review]
Good job

**Review by SilviaBarcellini — APPROVED** [review]
Very good job! 👍

**Pull request merged**
