### PR TITLE
➕  Add prettier

### PR DESCRIPTION
**Pull request by mrana17**
- Installed prettier with `npm i -D prettier`
- Added .prettierrc.json with default config
- Added .prettiergitignore to ignore build artifacts
- Add npm run prettify to format all code
- Prettified all code

https://prettier.io/docs/en/install.html

### CODE REVIEW

**Review by saschahaselhuhn — APPROVED** [review]
good job

**Review by christophvogel — APPROVED** [review]
GJ 👍

**Review by RonjaMeinecke — APPROVED** [review]
gj🚀

**Comment by HorstFrank** [comment]
YEAH! GJ!

**Pull request merged**
