### PR TITLE
➕  Add ESlint

### PR DESCRIPTION
**Pull request by mrana17**
- install ESLint `npm i -D eslint`
- configuration `npx eslint --init`
- add rules in .eslintrc.json
- add `"eslinter": "eslint ."`
- `npm install --save-dev eslint-config-prettier`
- add `"prettier"`to eslintrc.json
- add types

### CODE REVIEW

**Review by saschahaselhuhn — APPROVED** [review]
gj

**Review by M-Sieger — APPROVED** [review]
LGTM !

**Comment by RonjaMeinecke** [comment]
the L in ESLint is also in caps 😊

**Review by christophvogel — APPROVED** [review]
GJ 👍

**Pull request merged**
