### PR TITLE
➕ Add storybook

### PR DESCRIPTION
**Pull request by mrana17**
-

`npx sb init`
- Remove example stories folder
- Create components folder with example Button component
- Set stories folder in `.storybook/main.js`
- Load example component in `pages/index.tsx`
- Ignore
`/storybook-static`
- Add `.eslintignore`

### CODE REVIEW

**Review by christophvogel — APPROVED** [review]
GJ 👍

**Review by fre-ben — APPROVED** [review]
Truly amazing! 🚀

**Review by m-wiemers — APPROVED** [review]
If we were on Facebook, I would give you a Like 👍

**Review by cboenke — APPROVED** [review]
LGTM 🚀

**Comment by SilviaBarcellini** [comment]
Very good! 👍

**Pull request merged**
